### PR TITLE
Support the latest API schema

### PR DESCRIPTION
**Pull request by hsbt**
`client.users` returns the hash from the api endpoint of slack. I specified an attribute of `users` response.

### CODE REVIEW

**Comment by linyows** [comment]
Looking at the API docs now, indeed members were necessary for this code.
https://api.slack.com/methods/users.list

API specification updated? 🤔

**Comment by linyows** [comment]
I fixed tests here: https://github.com/pepabo/arisaid/pull/16

**Comment by linyows** [comment]
This change may not be necessary. Because it is handled by Slack API client. Here it is:
https://github.com/linyows/breacan/blob/master/lib/breacan/client.rb#L103-L114

**Comment by hsbt** [comment]
I'm not sure what the API specification. But It doesn't work now.

**Pull request closed without merging**
